addons:
  sonarcloud:
    organization: "heikoalexanderweber"
    token:
      secure: ${SONAR_TOKEN}

jobs:
  include:
    - stage: Build
      # OS
      os:
      - linux
      - osx
      - windows
      dist: trusty
      sudo: false

      language: go
      go:
      - 1.12.x
      install: true

      env:
      # can be removed when using Go version 1.13
      - GO111MODULE=on

      ### BEGIN LIFECYCLE ###
      before_install:
        - chmod -R +x ./
        - sh scripts/setup.sh
      script:
        - make build
      ### END LIFECYCLE ###

    - stage: Cover & Scan
      # OS
      os:
      - linux
      - osx
      - windows
      dist: trusty
      sudo: false

      language: go
      go:
      - 1.12.x
      install: true

      env:
      # can be removed when using Go version 1.13
      - GO111MODULE=on

      ### BEGIN LIFECYCLE ###
      before_install:
        - chmod -R +x ./
        - sh scripts/setup.sh
      script:
        - make cover
        - sonar-scanner -Dsonar.login=${SONAR_TOKEN} -Dsonar.branch.name=${TRAVIS_BRANCH}
      ### END LIFECYCLE ###
