version: "3.7"

services:
    raiding-raccoon:
        build:
            context: ../
            dockerfile: docker/Dockerfile.debug
        container_name: raiding-raccoon
        restart: "no"
        security_opt: 
            - "seccomp:unconfined"
        tty: true
        stdin_open: true
        ports:
            - 10101:10101 # delve debugging port
        environment:
            RR_REDIS_BACKBONE: docker_redis_1:6379
            RR_START_URL: https://orgadata.com
