version: "3.7"

services:
    redis:
        hostname: redis
        image: redis:latest
        restart: unless-stopped
        ports:
            - "127.0.0.1:6379:6379"

    redis-commander:
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: unless-stopped
        depends_on:
            - redis
        ports:
            - "127.0.0.1:6380:8081"
        environment:
            - REDIS_HOST=redis
