name: Default
on: [push]

jobs:
  test_and_scan:
    name: Test & Scan
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - uses: actions/checkout@v1
    - name: Install, test & cover
      working-directory: ./raiding-raccoon
      run: make test
    - name: Sonar scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      working-directory: ./raiding-raccoon
      run: make docker-build
