name: Build & Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Tag
      id: tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        RELEASE_BRANCHES: master
        DEFAULT_BUMP: patch
    - name: Build docker image
      working-directory: ./backend/log
      run: VERSION=${{ steps.tag.outputs.tag }} make docker-build
    - name: Push docker image to Github packages (versioned tag)
      id: gpr-versioned
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
        docker tag haw/raiding-raccoon:${{ steps.tag.outputs.tag }} docker.pkg.github.com/heikoalexanderweber/raiding-raccoon/raiding-raccoon:${{ steps.tag.outputs.tag }}
        docker push docker.pkg.github.com/heikoalexanderweber/raiding-raccoon/raiding-raccoon:${{ steps.tag.outputs.tag }}
    - name: Push docker image to Amazon ECR (versioned tag)
      id: ecr-versioned
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-central-1
        image: haw/raiding-raccoon:${{ steps.tag.outputs.tag }}
    - name: Push docker image to Amazon ECR (latest tag)
      id: ecr-latest
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-central-1
        image: haw/raiding-raccoon:latest
        local-image: haw/raiding-raccoon:${{ steps.tag.outputs.tag }}
